---
- name: ensure locales is installed
  apt: pkg={{ item }} state=latest update_cache=true cache_valid_time={{ apt_cache_valid_time }}
  with_items:
    - locales
    - language-pack-en
  register: locales_packages

- name: ensure dpkg is reconfigured
  command: dpkg-reconfigure locales
  when: locales_packages.changed

- name: ensure the system locale is configured
  locale_gen: name={{ item.locale }} state={{ item.state }}
  with_items: locale_locales